services:
  frontend:
    init: true
    build: ./frontend
    image: myreact
    container_name: front
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/srcs:/myreact/src
    networks:
      - hack
  backend:
    init: true
    build: ./backend
    image: mynodejs
    container_name: back
    ports:
      - "4000:4000"
    volumes:
      - ./backend/srcs:/srcs
    networks:
      - hack

networks:
  hack:
