services:
  frontend:
    init: true
    build: ./frontend
    image: myreact
    container_name: front
    ports:
      - "3000:80"
    environment:
      CLIENT_KEY: ${CLIENT_KEY}
      CLIENT_SECRET: ${CLIENT_SECRET}
    volumes:
      - ./frontend/srcs:/myreact/src
    networks:
      - hack
    depends_on:
      - backend
  backend:
    init: true
    build: ./backend
    image: mynodejs
    container_name: back
    environment:
      CLIENT_KEY: ${CLIENT_KEY}
      CLIENT_SECRET: ${CLIENT_SECRET}
    volumes:
      - ./backend/srcs:/srcs
    networks:
      - hack

networks:
  hack:
